version: "3"
services:          

    githubapi:
        build: ./containers/githubapi/.
        volumes:
            - ./containers/githubapi/content:/root
        depends_on: 
            - tracking.deployments

    server:
        build:
            context: ./
            dockerfile: ./containers/server/Dockerfile
        volumes:
            - ~/.featbranch/server:/usr/local/apache2/htdocs
        depends_on: 
            - app.reverseproxy

    site.buildbranch:
        build: ./containers/site.buildbranch/.
        volumes:
            - ~/.featbranch/server:/server
            - ~/.featbranch/repositories:/repositories
            - ./containers/site.buildbranch/content:/api

    data.buildbranch:
        build: ./containers/data.buildbranch/.
        volumes:
            - ~/.featbranch/server:/server
            - ~/.featbranch/repositories:/repositories
            - ./containers/data.buildbranch/content:/api

    data.buildpreview:
        build: ./containers/data.buildpreview/.
        volumes:
            - ~/.featbranch/server:/server
            - ~/.featbranch/repositories:/repositories
            - ./containers/data.buildpreview/content:/api
        depends_on: 
            - server

    site.a11yreport:
        build: ./containers/site.a11yreport/.
        volumes: 
            - ~/.featbranch/server:/server
            - ./containers/site.a11yreport/content:/api
        depends_on: 
            - server

    tracking.deployments:
        build: ./containers/tracking.deployments/.
        volumes:
            - ~/.featbranch/database:/database
            - ./containers/tracking.deployments/content:/root

    deploy.iteration:
        build: ./containers/deploy.iteration/.
        volumes:
            - ./containers/deploy.iteration/content:/root/deploy
        depends_on: 
            - githubapi
            - site.buildbranch

    dbinspect:
        build: ./containers/dbinspect/.
        volumes:
            - ~/.featbranch/database:/database

    slack:
        build: ./containers/slack/.
        volumes:
            - ./containers/slack/content:/root
            - ./slack/templates:/templates

    repo.update:
        build: ./containers/repo.update/.
        volumes:
            - ./containers/repo.update/content:/api
            - ~/.featbranch/repositories:/root

    deploy.loop:
        build: ./containers/deploy.loop
        volumes:
            - ./containers/deploy.loop/content:/api
        ports:
            - 8101:80

    app.settings:
        build: ./containers/app.settings/.
        volumes: 
            - ~/.featbranch/settings:/settings
            - ./containers/app.settings/content:/root/app

    app.reverseproxy:
        build: ./containers/app.reverseproxy/.
        ports:
            - 80:80
        restart: always